GET http://localhost:3000/subscribers

###
GET http://localhost:3000/subscribers/623ae38378459c4defaf3ccd

###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Arisa T",
    "subscribedToChannel": "Web Dev Simplified"
}